apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-operator-release
  namespace: kafka
spec:
  interval: 1m
  releaseName: kafka-operator
  values:
    installCRDs: true
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.30.0
      valuesFiles:
        - values.yaml
      sourceRef:
        kind: HelmRepository
        name: strimzi-kafka-repo
        namespace: default
